name: build_docker

on:
  watch:
    types: [started] #通过start手动触发

jobs:
  build_docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get APP_VERSION from Dockerfile
        id: get_app_version
        run: |
          APP_VERSION=$(grep 'ARG APP_VERSION=' Dockerfile | cut -d '=' -f 2)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/confluence:${{ env.APP_VERSION }}